<header id="header" class="page-topbar">
    <!-- start header nav-->
    <div class="navbar-fixed">
        <nav class="cyan">
            <div class="nav-wrapper container">
                <h1 class="logo-wrapper"><a href="index.php" class="brand-logo right darken-1">Intranet</a> <span class="logo-text">SistJ</span></h1>

                <!--<ul class="right hide-on-med-and-down">                    
                    <li>    
                        <a href="logout.php" class="waves-effect waves-block waves-light tooltipped" data-position="bottom" data-delay="50" data-tooltip="Salir"><i class="mdi-hardware-keyboard-tab"></i></a>                              
                    </li>
                </ul>-->
            </div>
        </nav>
    </div>
    <!-- end header nav-->
</header>