<footer class="page-footer">
    <div class="footer-copyright">
        <div class="container">
            <span>Copyright © 2017-2019 <a class="grey-text text-lighten-4" href="http://www.jashinsalazar.pe.hu" target="_blank">Mario Salazar</a> All rights reserved.</span>
            <span class="right"> Diseño y Desarrollo por <a class="grey-text text-lighten-4" href="http://www.jashinsalazar.pe.hu">Mario Salazar</a></span>
        </div>
    </div>
</footer>
